"""modulos de compras e producao
 
Revision ID: 2f4e1db947db
Revises: b64f3f26e783
Create Date: 2026-08-13 22:43:02.500452
 
"""
from typing import Sequence, Union
 
from alembic import op
import sqlalchemy as sa
import sqlmodel
 
 
# revision identifiers, used by Alembic.
revision: str = '2f4e1db947db'
down_revision: Union[str, Sequence[str], None] = 'b64f3f26e783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
 
 
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cnpj', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nome', name='uq_fornecedor_empresa_nome')
    )
    with op.batch_alter_table('fornecedor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fornecedor_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fornecedor_nome'), ['nome'], unique=False)
 
    op.create_table('pedidocompra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('numero', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('rascunho', 'aprovado', 'recebido', 'cancelado', name='statuspedido'), nullable=False),
    sa.Column('previsao_entrega', sa.Date(), nullable=True),
    sa.Column('observacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('aprovado_em', sa.DateTime(), nullable=True),
    sa.Column('recebido_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedidocompra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidocompra_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidocompra_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidocompra_fornecedor_id'), ['fornecedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidocompra_numero'), ['numero'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidocompra_status'), ['status'], unique=False)
 
    op.create_table('fichatecnica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'produto_id', name='uq_ficha_empresa_produto')
    )
    with op.batch_alter_table('fichatecnica', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fichatecnica_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fichatecnica_produto_id'), ['produto_id'], unique=False)
 
    op.create_table('itempedidocompra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('quantidade_recebida', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidocompra.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itempedidocompra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itempedidocompra_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itempedidocompra_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itempedidocompra_produto_id'), ['produto_id'], unique=False)
 
    op.create_table('ordemproducao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('numero', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('planejada', 'em_producao', 'concluida', 'cancelada', name='statusordem'), nullable=False),
    sa.Column('observacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('iniciada_em', sa.DateTime(), nullable=True),
    sa.Column('concluida_em', sa.DateTime(), nullable=True),
    sa.Column('custo_insumos', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ordemproducao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordemproducao_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordemproducao_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordemproducao_numero'), ['numero'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordemproducao_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordemproducao_status'), ['status'], unique=False)
 
    op.create_table('consumoordem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('ordem_id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('custo_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['insumo_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['ordem_id'], ['ordemproducao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consumoordem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consumoordem_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumoordem_insumo_id'), ['insumo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumoordem_ordem_id'), ['ordem_id'], unique=False)
 
    op.create_table('itemfichatecnica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('ficha_id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['ficha_id'], ['fichatecnica.id'], ),
    sa.ForeignKeyConstraint(['insumo_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itemfichatecnica', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itemfichatecnica_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itemfichatecnica_ficha_id'), ['ficha_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itemfichatecnica_insumo_id'), ['insumo_id'], unique=False)
 
    # ### end Alembic commands ###
 
 
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itemfichatecnica', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itemfichatecnica_insumo_id'))
        batch_op.drop_index(batch_op.f('ix_itemfichatecnica_ficha_id'))
        batch_op.drop_index(batch_op.f('ix_itemfichatecnica_empresa_id'))
 
    op.drop_table('itemfichatecnica')
    with op.batch_alter_table('consumoordem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consumoordem_ordem_id'))
        batch_op.drop_index(batch_op.f('ix_consumoordem_insumo_id'))
        batch_op.drop_index(batch_op.f('ix_consumoordem_empresa_id'))
 
    op.drop_table('consumoordem')
    with op.batch_alter_table('ordemproducao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordemproducao_status'))
        batch_op.drop_index(batch_op.f('ix_ordemproducao_produto_id'))
        batch_op.drop_index(batch_op.f('ix_ordemproducao_numero'))
        batch_op.drop_index(batch_op.f('ix_ordemproducao_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_ordemproducao_criado_em'))
 
    op.drop_table('ordemproducao')
    with op.batch_alter_table('itempedidocompra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itempedidocompra_produto_id'))
        batch_op.drop_index(batch_op.f('ix_itempedidocompra_pedido_id'))
        batch_op.drop_index(batch_op.f('ix_itempedidocompra_empresa_id'))
 
    op.drop_table('itempedidocompra')
    with op.batch_alter_table('fichatecnica', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fichatecnica_produto_id'))
        batch_op.drop_index(batch_op.f('ix_fichatecnica_empresa_id'))
 
    op.drop_table('fichatecnica')
    with op.batch_alter_table('pedidocompra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidocompra_status'))
        batch_op.drop_index(batch_op.f('ix_pedidocompra_numero'))
        batch_op.drop_index(batch_op.f('ix_pedidocompra_fornecedor_id'))
        batch_op.drop_index(batch_op.f('ix_pedidocompra_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_pedidocompra_criado_em'))
 
    op.drop_table('pedidocompra')
    with op.batch_alter_table('fornecedor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fornecedor_nome'))
        batch_op.drop_index(batch_op.f('ix_fornecedor_empresa_id'))
 
    op.drop_table('fornecedor')
    # ### end Alembic commands ###