"""estado inicial: multi-tenant, estoque, nota fiscal e lote
 
Revision ID: b64f3f26e783
Revises: 
Create Date: 2026-08-13 22:40:48.287041
 
"""
from typing import Sequence, Union
 
from alembic import op
import sqlalchemy as sa
import sqlmodel
 
 
# revision identifiers, used by Alembic.
revision: str = 'b64f3f26e783'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
 
 
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cnpj', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('exige_lote', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresa_cnpj'), ['cnpj'], unique=False)
        batch_op.create_index(batch_op.f('ix_empresa_nome'), ['nome'], unique=False)
 
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nome', name='uq_categoria_empresa_nome')
    )
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categoria_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categoria_nome'), ['nome'], unique=False)
 
    op.create_table('notafiscal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('numero', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fornecedor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notafiscal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notafiscal_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_notafiscal_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notafiscal_numero'), ['numero'], unique=False)
 
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senha_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('papel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuario_empresa_id'), ['empresa_id'], unique=False)
 
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unidade', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estoque_minimo', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Integer(), nullable=False),
    sa.Column('controla_lote', sa.Boolean(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'sku', name='uq_produto_empresa_sku')
    )
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produto_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_produto_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_produto_sku'), ['sku'], unique=False)
 
    op.create_table('itemnotafiscal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nota_fiscal_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('lote', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['nota_fiscal_id'], ['notafiscal.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itemnotafiscal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itemnotafiscal_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itemnotafiscal_lote'), ['lote'], unique=False)
        batch_op.create_index(batch_op.f('ix_itemnotafiscal_nota_fiscal_id'), ['nota_fiscal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itemnotafiscal_produto_id'), ['produto_id'], unique=False)
 
    op.create_table('movimentacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'saida', name='tipomovimentacao'), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('motivo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lote', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimentacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentacao_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacao_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacao_lote'), ['lote'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacao_produto_id'), ['produto_id'], unique=False)
 
    # ### end Alembic commands ###
 
 
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentacao_produto_id'))
        batch_op.drop_index(batch_op.f('ix_movimentacao_lote'))
        batch_op.drop_index(batch_op.f('ix_movimentacao_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_movimentacao_criado_em'))
 
    op.drop_table('movimentacao')
    with op.batch_alter_table('itemnotafiscal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itemnotafiscal_produto_id'))
        batch_op.drop_index(batch_op.f('ix_itemnotafiscal_nota_fiscal_id'))
        batch_op.drop_index(batch_op.f('ix_itemnotafiscal_lote'))
        batch_op.drop_index(batch_op.f('ix_itemnotafiscal_empresa_id'))
 
    op.drop_table('itemnotafiscal')
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produto_sku'))
        batch_op.drop_index(batch_op.f('ix_produto_nome'))
        batch_op.drop_index(batch_op.f('ix_produto_empresa_id'))
 
    op.drop_table('produto')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_usuario_email'))
 
    op.drop_table('usuario')
    with op.batch_alter_table('notafiscal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notafiscal_numero'))
        batch_op.drop_index(batch_op.f('ix_notafiscal_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_notafiscal_criado_em'))
 
    op.drop_table('notafiscal')
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categoria_nome'))
        batch_op.drop_index(batch_op.f('ix_categoria_empresa_id'))
 
    op.drop_table('categoria')
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresa_nome'))
        batch_op.drop_index(batch_op.f('ix_empresa_cnpj'))
 
    op.drop_table('empresa')
    # ### end Alembic commands ###